import { MambaSnapshot } from '../../../storybook/mamba/MambaSnapshot';
import { bannerCategory } from '../../../storybook/mamba/generated/banner.generated';

// Generated by scripts/generate-mamba-storybook.mjs. Do not edit manually.
const meta = {
  title: "Catalog/Mamba/Banner",
  parameters: {
    backgrounds: {
      default: 'game-hub-dark',
    },
  },
};

export default meta;

const { variants } = bannerCategory;

export const Banner1 = {
  name: "banner1",
  render: () => <MambaSnapshot entry={variants[0]} />,
  parameters: {
    docs: {
      source: {
        code: variants[0].renderedHtml,
      },
    },
  },
};

export const Banner2 = {
  name: "banner2",
  render: () => <MambaSnapshot entry={variants[1]} />,
  parameters: {
    docs: {
      source: {
        code: variants[1].renderedHtml,
      },
    },
  },
};
