import { MambaSnapshot } from '../../../storybook/mamba/MambaSnapshot';
import { blogCategory } from '../../../storybook/mamba/generated/blog.generated';

// Generated by scripts/generate-mamba-storybook.mjs. Do not edit manually.
const meta = {
  title: "Catalog/Mamba/Blog",
  parameters: {
    backgrounds: {
      default: 'game-hub-dark',
    },
  },
};

export default meta;

const { variants } = blogCategory;

export const Blog6 = {
  name: "blog6",
  render: () => <MambaSnapshot entry={variants[0]} />,
  parameters: {
    docs: {
      source: {
        code: variants[0].renderedHtml,
      },
    },
  },
};

export const Blog7 = {
  name: "blog7",
  render: () => <MambaSnapshot entry={variants[1]} />,
  parameters: {
    docs: {
      source: {
        code: variants[1].renderedHtml,
      },
    },
  },
};

export const Blog5 = {
  name: "blog5",
  render: () => <MambaSnapshot entry={variants[2]} />,
  parameters: {
    docs: {
      source: {
        code: variants[2].renderedHtml,
      },
    },
  },
};

export const Blog3 = {
  name: "blog3",
  render: () => <MambaSnapshot entry={variants[3]} />,
  parameters: {
    docs: {
      source: {
        code: variants[3].renderedHtml,
      },
    },
  },
};

export const Blog1 = {
  name: "blog1",
  render: () => <MambaSnapshot entry={variants[4]} />,
  parameters: {
    docs: {
      source: {
        code: variants[4].renderedHtml,
      },
    },
  },
};

export const Blog2 = {
  name: "blog2",
  render: () => <MambaSnapshot entry={variants[5]} />,
  parameters: {
    docs: {
      source: {
        code: variants[5].renderedHtml,
      },
    },
  },
};

export const Blog4 = {
  name: "blog4",
  render: () => <MambaSnapshot entry={variants[6]} />,
  parameters: {
    docs: {
      source: {
        code: variants[6].renderedHtml,
      },
    },
  },
};
