import { MambaSnapshot } from '../../../storybook/mamba/MambaSnapshot';
import { breadcrumbCategory } from '../../../storybook/mamba/generated/breadcrumb.generated';

// Generated by scripts/generate-mamba-storybook.mjs. Do not edit manually.
const meta = {
  title: "Catalog/Mamba/Breadcrumb",
  parameters: {
    backgrounds: {
      default: 'game-hub-dark',
    },
  },
};

export default meta;

const { variants } = breadcrumbCategory;

export const Breadcrumb1 = {
  name: "breadcrumb1",
  render: () => <MambaSnapshot entry={variants[0]} />,
  parameters: {
    docs: {
      source: {
        code: variants[0].renderedHtml,
      },
    },
  },
};

export const Breadcrumb2 = {
  name: "breadcrumb2",
  render: () => <MambaSnapshot entry={variants[1]} />,
  parameters: {
    docs: {
      source: {
        code: variants[1].renderedHtml,
      },
    },
  },
};
