import { MambaSnapshot } from '../../../storybook/mamba/MambaSnapshot';
import { callToActionCategory } from '../../../storybook/mamba/generated/call-to-action.generated';

// Generated by scripts/generate-mamba-storybook.mjs. Do not edit manually.
const meta = {
  title: "Catalog/Mamba/Call to Action",
  parameters: {
    backgrounds: {
      default: 'game-hub-dark',
    },
  },
};

export default meta;

const { variants } = callToActionCategory;

export const Cta1 = {
  name: "cta1",
  render: () => <MambaSnapshot entry={variants[0]} />,
  parameters: {
    docs: {
      source: {
        code: variants[0].renderedHtml,
      },
    },
  },
};

export const Cta2 = {
  name: "cta2",
  render: () => <MambaSnapshot entry={variants[1]} />,
  parameters: {
    docs: {
      source: {
        code: variants[1].renderedHtml,
      },
    },
  },
};

export const Cta3 = {
  name: "cta3",
  render: () => <MambaSnapshot entry={variants[2]} />,
  parameters: {
    docs: {
      source: {
        code: variants[2].renderedHtml,
      },
    },
  },
};

export const Cta4 = {
  name: "cta4",
  render: () => <MambaSnapshot entry={variants[3]} />,
  parameters: {
    docs: {
      source: {
        code: variants[3].renderedHtml,
      },
    },
  },
};

export const Cta5 = {
  name: "cta5",
  render: () => <MambaSnapshot entry={variants[4]} />,
  parameters: {
    docs: {
      source: {
        code: variants[4].renderedHtml,
      },
    },
  },
};

export const Cta6 = {
  name: "cta6",
  render: () => <MambaSnapshot entry={variants[5]} />,
  parameters: {
    docs: {
      source: {
        code: variants[5].renderedHtml,
      },
    },
  },
};
