import { MambaSnapshot } from '../../../storybook/mamba/MambaSnapshot';
import { cardCategory } from '../../../storybook/mamba/generated/card.generated';

// Generated by scripts/generate-mamba-storybook.mjs. Do not edit manually.
const meta = {
  title: "Catalog/Mamba/Card",
  parameters: {
    backgrounds: {
      default: 'game-hub-dark',
    },
  },
};

export default meta;

const { variants } = cardCategory;

export const Card5 = {
  name: "card5",
  render: () => <MambaSnapshot entry={variants[0]} />,
  parameters: {
    docs: {
      source: {
        code: variants[0].renderedHtml,
      },
    },
  },
};

export const Card1 = {
  name: "card1",
  render: () => <MambaSnapshot entry={variants[1]} />,
  parameters: {
    docs: {
      source: {
        code: variants[1].renderedHtml,
      },
    },
  },
};

export const Card2 = {
  name: "card2",
  render: () => <MambaSnapshot entry={variants[2]} />,
  parameters: {
    docs: {
      source: {
        code: variants[2].renderedHtml,
      },
    },
  },
};

export const Card3 = {
  name: "card3",
  render: () => <MambaSnapshot entry={variants[3]} />,
  parameters: {
    docs: {
      source: {
        code: variants[3].renderedHtml,
      },
    },
  },
};

export const Card4 = {
  name: "card4",
  render: () => <MambaSnapshot entry={variants[4]} />,
  parameters: {
    docs: {
      source: {
        code: variants[4].renderedHtml,
      },
    },
  },
};
