import { MambaSnapshot } from '../../../storybook/mamba/MambaSnapshot';
import { faqCategory } from '../../../storybook/mamba/generated/faq.generated';

// Generated by scripts/generate-mamba-storybook.mjs. Do not edit manually.
const meta = {
  title: "Catalog/Mamba/FAQ",
  parameters: {
    backgrounds: {
      default: 'game-hub-dark',
    },
  },
};

export default meta;

const { variants } = faqCategory;

export const Faq1 = {
  name: "faq1",
  render: () => <MambaSnapshot entry={variants[0]} />,
  parameters: {
    docs: {
      source: {
        code: variants[0].renderedHtml,
      },
    },
  },
};

export const Faq5 = {
  name: "faq5",
  render: () => <MambaSnapshot entry={variants[1]} />,
  parameters: {
    docs: {
      source: {
        code: variants[1].renderedHtml,
      },
    },
  },
};

export const Faq2 = {
  name: "faq2",
  render: () => <MambaSnapshot entry={variants[2]} />,
  parameters: {
    docs: {
      source: {
        code: variants[2].renderedHtml,
      },
    },
  },
};

export const Faq3 = {
  name: "faq3",
  render: () => <MambaSnapshot entry={variants[3]} />,
  parameters: {
    docs: {
      source: {
        code: variants[3].renderedHtml,
      },
    },
  },
};

export const Faq4 = {
  name: "faq4",
  render: () => <MambaSnapshot entry={variants[4]} />,
  parameters: {
    docs: {
      source: {
        code: variants[4].renderedHtml,
      },
    },
  },
};

export const Faq6 = {
  name: "faq6",
  render: () => <MambaSnapshot entry={variants[5]} />,
  parameters: {
    docs: {
      source: {
        code: variants[5].renderedHtml,
      },
    },
  },
};
