import { MambaSnapshot } from '../../../storybook/mamba/MambaSnapshot';
import { featureCategory } from '../../../storybook/mamba/generated/feature.generated';

// Generated by scripts/generate-mamba-storybook.mjs. Do not edit manually.
const meta = {
  title: 'Catalog/Mamba/Feature',
  parameters: {
    backgrounds: {
      default: 'game-hub-dark',
    },
  },
};

export default meta;

const { variants } = featureCategory;

export const Feature1 = {
  name: 'feature1',
  render: () => <MambaSnapshot entry={variants[0]} />,
  parameters: {
    docs: {
      source: {
        code: variants[0].renderedHtml,
      },
    },
  },
};

export const Feature2 = {
  name: 'feature2',
  render: () => <MambaSnapshot entry={variants[1]} />,
  parameters: {
    docs: {
      source: {
        code: variants[1].renderedHtml,
      },
    },
  },
};

export const Feature3 = {
  name: 'feature3',
  render: () => <MambaSnapshot entry={variants[2]} />,
  parameters: {
    docs: {
      source: {
        code: variants[2].renderedHtml,
      },
    },
  },
};

export const Feature4 = {
  name: 'feature4',
  render: () => <MambaSnapshot entry={variants[3]} />,
  parameters: {
    docs: {
      source: {
        code: variants[3].renderedHtml,
      },
    },
  },
};

export const Feature5 = {
  name: 'feature5',
  render: () => <MambaSnapshot entry={variants[4]} />,
  parameters: {
    docs: {
      source: {
        code: variants[4].renderedHtml,
      },
    },
  },
};

export const Feature6 = {
  name: 'feature6',
  render: () => <MambaSnapshot entry={variants[5]} />,
  parameters: {
    docs: {
      source: {
        code: variants[5].renderedHtml,
      },
    },
  },
};

export const Feature7 = {
  name: 'feature7',
  render: () => <MambaSnapshot entry={variants[6]} />,
  parameters: {
    docs: {
      source: {
        code: variants[6].renderedHtml,
      },
    },
  },
};

export const Feature8 = {
  name: 'feature8',
  render: () => <MambaSnapshot entry={variants[7]} />,
  parameters: {
    docs: {
      source: {
        code: variants[7].renderedHtml,
      },
    },
  },
};
