import { MambaSnapshot } from '../../../storybook/mamba/MambaSnapshot';
import { footerCategory } from '../../../storybook/mamba/generated/footer.generated';

// Generated by scripts/generate-mamba-storybook.mjs. Do not edit manually.
const meta = {
  title: 'Catalog/Mamba/Footer',
  parameters: {
    backgrounds: {
      default: 'game-hub-dark',
    },
  },
};

export default meta;

const { variants } = footerCategory;

export const Footer1 = {
  name: 'footer1',
  render: () => <MambaSnapshot entry={variants[0]} />,
  parameters: {
    docs: {
      source: {
        code: variants[0].renderedHtml,
      },
    },
  },
};

export const Footer2 = {
  name: 'footer2',
  render: () => <MambaSnapshot entry={variants[1]} />,
  parameters: {
    docs: {
      source: {
        code: variants[1].renderedHtml,
      },
    },
  },
};

export const Footer3 = {
  name: 'footer3',
  render: () => <MambaSnapshot entry={variants[2]} />,
  parameters: {
    docs: {
      source: {
        code: variants[2].renderedHtml,
      },
    },
  },
};

export const Footer4 = {
  name: 'footer4',
  render: () => <MambaSnapshot entry={variants[3]} />,
  parameters: {
    docs: {
      source: {
        code: variants[3].renderedHtml,
      },
    },
  },
};

export const Footer5 = {
  name: 'footer5',
  render: () => <MambaSnapshot entry={variants[4]} />,
  parameters: {
    docs: {
      source: {
        code: variants[4].renderedHtml,
      },
    },
  },
};
