import { MambaSnapshot } from '../../../storybook/mamba/MambaSnapshot';
import { formCategory } from '../../../storybook/mamba/generated/form.generated';

// Generated by scripts/generate-mamba-storybook.mjs. Do not edit manually.
const meta = {
  title: "Catalog/Mamba/Form",
  parameters: {
    backgrounds: {
      default: 'game-hub-dark',
    },
  },
};

export default meta;

const { variants } = formCategory;

export const Form1 = {
  name: "form1",
  render: () => <MambaSnapshot entry={variants[0]} />,
  parameters: {
    docs: {
      source: {
        code: variants[0].renderedHtml,
      },
    },
  },
};
