import { MambaSnapshot } from '../../../storybook/mamba/MambaSnapshot';
import { galleryCategory } from '../../../storybook/mamba/generated/gallery.generated';

// Generated by scripts/generate-mamba-storybook.mjs. Do not edit manually.
const meta = {
  title: "Catalog/Mamba/Gallery",
  parameters: {
    backgrounds: {
      default: 'game-hub-dark',
    },
  },
};

export default meta;

const { variants } = galleryCategory;

export const Gallery1 = {
  name: "gallery1",
  render: () => <MambaSnapshot entry={variants[0]} />,
  parameters: {
    docs: {
      source: {
        code: variants[0].renderedHtml,
      },
    },
  },
};

export const Gallery2 = {
  name: "gallery2",
  render: () => <MambaSnapshot entry={variants[1]} />,
  parameters: {
    docs: {
      source: {
        code: variants[1].renderedHtml,
      },
    },
  },
};
