import { MambaSnapshot } from '../../../storybook/mamba/MambaSnapshot';
import { loadingCategory } from '../../../storybook/mamba/generated/loading.generated';

// Generated by scripts/generate-mamba-storybook.mjs. Do not edit manually.
const meta = {
  title: 'Catalog/Mamba/Loading',
  parameters: {
    backgrounds: {
      default: 'game-hub-dark',
    },
  },
};

export default meta;

const { variants } = loadingCategory;

export const Loading1 = {
  name: 'loading1',
  render: () => <MambaSnapshot entry={variants[0]} />,
  parameters: {
    docs: {
      source: {
        code: variants[0].renderedHtml,
      },
    },
  },
};

export const Loading2 = {
  name: 'loading2',
  render: () => <MambaSnapshot entry={variants[1]} />,
  parameters: {
    docs: {
      source: {
        code: variants[1].renderedHtml,
      },
    },
  },
};
