import { MambaSnapshot } from '../../../storybook/mamba/MambaSnapshot';
import { loginCategory } from '../../../storybook/mamba/generated/login.generated';

// Generated by scripts/generate-mamba-storybook.mjs. Do not edit manually.
const meta = {
  title: "Catalog/Mamba/Login",
  parameters: {
    backgrounds: {
      default: 'game-hub-dark',
    },
  },
};

export default meta;

const { variants } = loginCategory;

export const Login3 = {
  name: "login3",
  render: () => <MambaSnapshot entry={variants[0]} />,
  parameters: {
    docs: {
      source: {
        code: variants[0].renderedHtml,
      },
    },
  },
};

export const Login4 = {
  name: "login4",
  render: () => <MambaSnapshot entry={variants[1]} />,
  parameters: {
    docs: {
      source: {
        code: variants[1].renderedHtml,
      },
    },
  },
};

export const Login1 = {
  name: "login1",
  render: () => <MambaSnapshot entry={variants[2]} />,
  parameters: {
    docs: {
      source: {
        code: variants[2].renderedHtml,
      },
    },
  },
};

export const Login2 = {
  name: "login2",
  render: () => <MambaSnapshot entry={variants[3]} />,
  parameters: {
    docs: {
      source: {
        code: variants[3].renderedHtml,
      },
    },
  },
};

export const Login5 = {
  name: "login5",
  render: () => <MambaSnapshot entry={variants[4]} />,
  parameters: {
    docs: {
      source: {
        code: variants[4].renderedHtml,
      },
    },
  },
};
