import { MambaSnapshot } from '../../../storybook/mamba/MambaSnapshot';
import { pricingCategory } from '../../../storybook/mamba/generated/pricing.generated';

// Generated by scripts/generate-mamba-storybook.mjs. Do not edit manually.
const meta = {
  title: 'Catalog/Mamba/Pricing',
  parameters: {
    backgrounds: {
      default: 'game-hub-dark',
    },
  },
};

export default meta;

const { variants } = pricingCategory;

export const Pricing5 = {
  name: 'pricing5',
  render: () => <MambaSnapshot entry={variants[0]} />,
  parameters: {
    docs: {
      source: {
        code: variants[0].renderedHtml,
      },
    },
  },
};

export const Pricing4 = {
  name: 'pricing4',
  render: () => <MambaSnapshot entry={variants[1]} />,
  parameters: {
    docs: {
      source: {
        code: variants[1].renderedHtml,
      },
    },
  },
};

export const Pricing2 = {
  name: 'pricing2',
  render: () => <MambaSnapshot entry={variants[2]} />,
  parameters: {
    docs: {
      source: {
        code: variants[2].renderedHtml,
      },
    },
  },
};

export const Pricing1 = {
  name: 'pricing1',
  render: () => <MambaSnapshot entry={variants[3]} />,
  parameters: {
    docs: {
      source: {
        code: variants[3].renderedHtml,
      },
    },
  },
};

export const Pricing3 = {
  name: 'pricing3',
  render: () => <MambaSnapshot entry={variants[4]} />,
  parameters: {
    docs: {
      source: {
        code: variants[4].renderedHtml,
      },
    },
  },
};
