import { MambaSnapshot } from '../../../storybook/mamba/MambaSnapshot';
import { shoppingCartCategory } from '../../../storybook/mamba/generated/shopping-cart.generated';

// Generated by scripts/generate-mamba-storybook.mjs. Do not edit manually.
const meta = {
  title: "Catalog/Mamba/Shopping Cart",
  parameters: {
    backgrounds: {
      default: 'game-hub-dark',
    },
  },
};

export default meta;

const { variants } = shoppingCartCategory;

export const Cart1 = {
  name: "cart1",
  render: () => <MambaSnapshot entry={variants[0]} />,
  parameters: {
    docs: {
      source: {
        code: variants[0].renderedHtml,
      },
    },
  },
};

export const Cart2 = {
  name: "cart2",
  render: () => <MambaSnapshot entry={variants[1]} />,
  parameters: {
    docs: {
      source: {
        code: variants[1].renderedHtml,
      },
    },
  },
};
