import { MambaSnapshot } from '../../../storybook/mamba/MambaSnapshot';
import { skeletonLoaderCategory } from '../../../storybook/mamba/generated/skeleton-loader.generated';

// Generated by scripts/generate-mamba-storybook.mjs. Do not edit manually.
const meta = {
  title: 'Catalog/Mamba/Skeleton Loader',
  parameters: {
    backgrounds: {
      default: 'game-hub-dark',
    },
  },
};

export default meta;

const { variants } = skeletonLoaderCategory;

export const Skeleton1 = {
  name: 'skeleton1',
  render: () => <MambaSnapshot entry={variants[0]} />,
  parameters: {
    docs: {
      source: {
        code: variants[0].renderedHtml,
      },
    },
  },
};

export const Skeleton2 = {
  name: 'skeleton2',
  render: () => <MambaSnapshot entry={variants[1]} />,
  parameters: {
    docs: {
      source: {
        code: variants[1].renderedHtml,
      },
    },
  },
};
