import { MambaSnapshot } from '../../../storybook/mamba/MambaSnapshot';
import { snackbarCategory } from '../../../storybook/mamba/generated/snackbar.generated';

// Generated by scripts/generate-mamba-storybook.mjs. Do not edit manually.
const meta = {
  title: "Catalog/Mamba/Snackbar",
  parameters: {
    backgrounds: {
      default: 'game-hub-dark',
    },
  },
};

export default meta;

const { variants } = snackbarCategory;

export const Snackbar4 = {
  name: "snackbar4",
  render: () => <MambaSnapshot entry={variants[0]} />,
  parameters: {
    docs: {
      source: {
        code: variants[0].renderedHtml,
      },
    },
  },
};

export const Snackbar5 = {
  name: "snackbar5",
  render: () => <MambaSnapshot entry={variants[1]} />,
  parameters: {
    docs: {
      source: {
        code: variants[1].renderedHtml,
      },
    },
  },
};

export const Snackbar6 = {
  name: "snackbar6",
  render: () => <MambaSnapshot entry={variants[2]} />,
  parameters: {
    docs: {
      source: {
        code: variants[2].renderedHtml,
      },
    },
  },
};

export const Snackbar1 = {
  name: "snackbar1",
  render: () => <MambaSnapshot entry={variants[3]} />,
  parameters: {
    docs: {
      source: {
        code: variants[3].renderedHtml,
      },
    },
  },
};

export const Snackbar2 = {
  name: "snackbar2",
  render: () => <MambaSnapshot entry={variants[4]} />,
  parameters: {
    docs: {
      source: {
        code: variants[4].renderedHtml,
      },
    },
  },
};

export const Snackbar3 = {
  name: "snackbar3",
  render: () => <MambaSnapshot entry={variants[5]} />,
  parameters: {
    docs: {
      source: {
        code: variants[5].renderedHtml,
      },
    },
  },
};
