import { MambaSnapshot } from '../../../storybook/mamba/MambaSnapshot';
import { stepsCategory } from '../../../storybook/mamba/generated/steps.generated';

// Generated by scripts/generate-mamba-storybook.mjs. Do not edit manually.
const meta = {
  title: "Catalog/Mamba/Steps",
  parameters: {
    backgrounds: {
      default: 'game-hub-dark',
    },
  },
};

export default meta;

const { variants } = stepsCategory;

export const Steps4 = {
  name: "steps4",
  render: () => <MambaSnapshot entry={variants[0]} />,
  parameters: {
    docs: {
      source: {
        code: variants[0].renderedHtml,
      },
    },
  },
};

export const Steps3 = {
  name: "steps3",
  render: () => <MambaSnapshot entry={variants[1]} />,
  parameters: {
    docs: {
      source: {
        code: variants[1].renderedHtml,
      },
    },
  },
};

export const Steps2 = {
  name: "steps2",
  render: () => <MambaSnapshot entry={variants[2]} />,
  parameters: {
    docs: {
      source: {
        code: variants[2].renderedHtml,
      },
    },
  },
};

export const Steps1 = {
  name: "steps1",
  render: () => <MambaSnapshot entry={variants[3]} />,
  parameters: {
    docs: {
      source: {
        code: variants[3].renderedHtml,
      },
    },
  },
};
