import { MambaSnapshot } from '../../../storybook/mamba/MambaSnapshot';
import { timelineCategory } from '../../../storybook/mamba/generated/timeline.generated';

// Generated by scripts/generate-mamba-storybook.mjs. Do not edit manually.
const meta = {
  title: 'Catalog/Mamba/Timeline',
  parameters: {
    backgrounds: {
      default: 'game-hub-dark',
    },
  },
};

export default meta;

const { variants } = timelineCategory;

export const Timeline5 = {
  name: 'timeline5',
  render: () => <MambaSnapshot entry={variants[0]} />,
  parameters: {
    docs: {
      source: {
        code: variants[0].renderedHtml,
      },
    },
  },
};

export const Timeline1 = {
  name: 'timeline1',
  render: () => <MambaSnapshot entry={variants[1]} />,
  parameters: {
    docs: {
      source: {
        code: variants[1].renderedHtml,
      },
    },
  },
};

export const Timeline2 = {
  name: 'timeline2',
  render: () => <MambaSnapshot entry={variants[2]} />,
  parameters: {
    docs: {
      source: {
        code: variants[2].renderedHtml,
      },
    },
  },
};

export const Timeline4 = {
  name: 'timeline4',
  render: () => <MambaSnapshot entry={variants[3]} />,
  parameters: {
    docs: {
      source: {
        code: variants[3].renderedHtml,
      },
    },
  },
};

export const Timeline3 = {
  name: 'timeline3',
  render: () => <MambaSnapshot entry={variants[4]} />,
  parameters: {
    docs: {
      source: {
        code: variants[4].renderedHtml,
      },
    },
  },
};
