import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const prompt = 'To prove this works, I want you to output the following: Hello World! How are you?';
const agents = ['gilfoyle', 'solid-snake', 'teddy', 'gordon-ramsay', 'mad-max'];

describe('agent prompt proof workflows', () => {
  it('queues five trusted prompt runs for every pull request', () => {
    const trigger = readFileSync(path.join(root, '.github/workflows/agent-prompt-proof-trigger.yml'), 'utf8');

    expect(trigger).toContain('name: Agent Prompt Proof Trigger');
    expect(trigger).toContain('pull_request:');

    for (const agent of agents) {
      const source = readFileSync(path.join(root, `.github/workflows/${agent}-prompt-proof.md`), 'utf8');
      const lock = readFileSync(path.join(root, `.github/workflows/${agent}-prompt-proof.lock.yml`), 'utf8');

      expect(source.trimEnd().endsWith(prompt)).toBe(true);
      expect(source).toContain('workflows: [Agent Prompt Proof Trigger]');
      expect(source).toContain('name: Print prompt response');
      expect(source).toContain('prompt-output:');
      expect(source).toContain('threat-detection: false');
      expect(lock).toContain('This file was automatically generated by gh-aw');
      expect(lock).toContain('Tools: missing_tool, missing_data, noop, prompt_output');
      expect(lock).not.toContain("item.type === 'create_issue'");
    }
  });
});
